In [10]:
import numpy as np
gfg = np.matrix('[4,1,9;12,3,1;4,5,6]')

total_sum=np.sum(gfg)
row_sum=np.sum(gfg,axis=1)
column_sum=np.sum(gfg,axis=0)

print(total_sum)
print(row_sum)
print(column_sum)



45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [20]:
import numpy as np
array= np.array([10,52,62,16,16,54,453])

sorted_array=np.sort(array)
sorted_indices=np.argsort(array)
smallest_elements=np.sort(array)[:4]
largest_elements=np.sort(array)[-5:]

print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 smallest elements:", smallest_elements)
print("5 largest elements:", largest_elements)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [32]:
import numpy as np
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integer_element = array[np.floor(array) == array]
float_element =array[np.floor(array) != array]

print(integer_element)
print(float_element)

[1. 2. 3. 2.]
[1.2 2.2]


In [34]:

import numpy as np

X = ord('R') + ord('G') 
sales = np.array([X, X+50, X+100, X+150, X+200])

tax_rate = ((X % 5) + 5) / 100
tax_amount = sales * tax_rate

discounted_sales = np.where(sales < X+100, sales * 0.95, sales * 0.90)

weeks = 3
weekly_sales = np.vstack([discounted_sales * (1 + i * 0.02) for i in range(weeks)])

# Print results
print("Sales Array:", sales)
print("Tax Rate:", tax_rate)
print("Tax Amount:", tax_amount)
print("Discounted Sales:", discounted_sales)
print("Weekly Sales:\n", weekly_sales)



Sales Array: [153 203 253 303 353]
Tax Rate: 0.08
Tax Amount: [12.24 16.24 20.24 24.24 28.24]
Discounted Sales: [145.35 192.85 227.7  272.7  317.7 ]
Weekly Sales:
 [[145.35  192.85  227.7   272.7   317.7  ]
 [148.257 196.707 232.254 278.154 324.054]
 [151.164 200.564 236.808 283.608 330.408]]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-10, 10, 100)

y_square = x**2
y_sin = np.sin(x)
y_exp = np.exp(x)
y_log = np.log(np.abs(x) + 1)

plt.figure(figsize=(10, 6))

plt.plot(x, y_square, label=r'y=x^2
', color='blue', linewidth=2)
plt.plot(x, y_sin, label=r'y=sin(x)
', color='red', linewidth=2)
plt.plot(x, y_exp, label=r'y=e^x
', color='green', linewidth=2)
plt.plot(x, y_log, label=r'y=log(|x98)
', color='purple', linewidth=2)

plt.ylim(-5, 50)

plt.title("Plots of Various Functions", fontsize=14)
plt.xlabel("x values", fontsize=12)
plt.ylabel("y values", fontsize=12)
plt.axhline(0, color='black', linewidth=0.8)
plt.axvline(0, color='black', linewidth=0.8)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()
plt.show()